version: '3.7'
services:
  calc-app-backend:
    container_name: calc-app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
      - ./backend/public:/app/public
    command: npm run dev
    ports:
      - 8000:8000
    depends_on:
      - calc-app-postgres
      - calc-app-redis

  calc-app-frontend:
    container_name: calc-app-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    command: npm run dev
    ports:
      - '3000:3000'

  calc-app-postgres:
    container_name: calc-app-postgres
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calcapp

  calc-app-redis:
    container_name: calc-app-redis
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  calc-app-pgadmin:
    container_name: calc-app-pgadmin
    image: dpage/pgadmin4:latest
    depends_on:
      - calc-app-postgres
    ports:
      - 9000:9000
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=9000

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
